### ISSUE TITLE
Shift + draw line sometimes creates selection box

### ISSUE THREAD

**Issue by rabidsquirrel117** [conundrumer/lr#16]
![screen shot 2015-09-05 at 8 17 47 am](https://cloud.githubusercontent.com/assets/14138599/9699387/bded3994-53a6-11e5-8bf5-ccde096d56b3.png)

**Comment by rabidsquirrel117** [comment]
For me, everytime I hold shift and draw lines, the first time is a selection box, and then it starts drawing shifted lines

**Comment by conundrumer** [comment]
does this happen on any other webpage? I'm not sure if I have control over this, and I'd have to test with your computer (which we can do realtime actually)

**Comment by conundrumer** [comment]
has this ever come up again?

**Comment by rabidsquirrel117** [comment]
It came up consistently when I first tested it but didn't in the 5 hours I streamed.

However, OTDE had a similar glitch which you can see about 30 seconds into this broadcast archive http://www.twitch.tv/weridethelinescommunity/v/27477181

**Comment by conundrumer** [comment]
labeling as wontfix until there is a way to reproduce

**Comment by rabidsquirrel117** [comment]
it happens if it hit and hold shift, and then click and drag

if I hit shift while dragging, or if  it doesn't happen

**Comment by conundrumer** [comment]
Chrome extensions such as [Linkclump](https://chrome.google.com/webstore/detail/linkclump/lfpjkncokllnfokkgpkobnkbkmelfefj?hl=en) may cause unexpected behavior.
