### ISSUE TITLE
No line ID management

### ISSUE THREAD

**Issue by benwubbleyou** [conundrumer/lr#18]
I loaded up a sol of mine and tried to start playing with it and after I tried to draw a line the physics breaks, making Bosh crash a line he didn't crash on before.

**Comment by conundrumer** [comment]
Oh darn, I know why that happened. Basically, each line has an ID number, but I temporarily made new lines start from 0, but that means lines get replaced and stuff breaks.

**Comment by benwubbleyou** [comment]
Crazy, I had no idea that's how it worked. Let me know when this works!

**Comment by conundrumer** [comment]
pushed fix
