### ISSUE TITLE
Allow manual selection of eraser size and show outline

### ISSUE THREAD

**Issue by DanielOaks** [conundrumer/lr#2]
It'd be nice to be able to choose the size of the eraser, maybe when you click on it a dropdown could pop up with several different eraser sizes from small to large. As well, especially with the larger sizes, being able to see the radius of the eraser (maybe hiding the cursor and replacing it with a circle) would be useful.

**Comment by conundrumer** [comment]
Showing custom cursors for each tool is something that should be obvious but somehow I completely forgot. I'll add in a custom cursor for the eraser that corresponds to its size.

I plan to add a selection tool where you can make selections by clicking on individual lines or through rectangular selection, and then delete the selected lines (along with moving them and dragging the endpoints). That means you'd be able to delete large numbers of line in an area, or remove individual lines in a dense area. With that level of precision, I feel that custom eraser sizes don't add much.

**Comment by DanielOaks** [comment]
That's fair enough. I think at least something like a small/medium/large could be helpful, mostly in that it can be easier to just have a brush-like thing that just wipes out everything it touches, when you want to erase specific parts and redraw them, but whatever works!

**Comment by conundrumer** [comment]
closing in favor of #51
