### ISSUE TITLE
gets stuck in onion skin until flag is reached 

### ISSUE THREAD

**Issue by SheldonLR** [conundrumer/lr#38]
onion skin lags horribly and i lost progress

**Comment by SheldonLR** [comment]
onion skin lags horribly and i lost progress

**Comment by conundrumer** [comment]
Sorry, I don't understand the circumstance here. Onion skin spans the time between the current time and the flag (which may be at the start). I'm aware it's really laggy right now, but for now, you should be careful when you use onion skin to make sure it doesn't span too much time.

**Comment by conundrumer** [comment]
closing in favor of #15
