### ISSUE TITLE
selection filter

### ISSUE THREAD

**Issue by rabidsquirrel117** [conundrumer/lr#55]
erase only one color of lines

also for select tool

**Comment by conundrumer** [comment]
what ifi we had layers instead

**Comment by rabidsquirrel117** [comment]
How would you select specific lines and not others to assign them to the layers?

**Comment by conundrumer** [comment]
i think i'll have some advanced select tool options (like in illlustrator) instead of overloading the eraser

**Comment by conundrumer** [comment]
current workaround: use select tool and select carefully

**Comment by conundrumer** [comment]
closing in favor of #65
