### ISSUE TITLE
White gap on bottom of Bosh's sled

### ISSUE THREAD

**Issue by rabidsquirrel117** [conundrumer/lr#59]
![screen shot 2015-11-26 at 9 09 13 pm](https://cloud.githubusercontent.com/assets/14138599/11433401/0eed61b8-9482-11e5-898d-f3c6229ba74a.png)

**Comment by conundrumer** [comment]
this is a bug with chrome

it'll get fixed if you wait it out or if you use a different browser in the mean time

**Comment by rabidsquirrel117** [comment]
No big, it's a very small complaint!
