### ISSUE TITLE
Indicated contacts that cause death

### ISSUE THREAD

**Issue by SheldonLR** [conundrumer/lr#68]
responsive live editing, when you use line adjust during playback, the current frame will begin updating immediately. Before, it would only begin once you applied the change by releasing the mouse.
live editing preference
--->>"Show contact lines" is much different now. It now indicates if the next frame will die, and what contact line is responsible by appearing as an orange line. Rider and sled breaks for the next frame turn the contact points dark blue.<-----
added 16x playback
bugfix involving snapping one line to the same line twice.
bugfix where high update speeds wouldn't actually hit the speed intended.

saw anton use it in lra
possible color scheme:
grey for skeleton and black for points

**Comment by rabidsquirrel117** [comment]
+1
sometimes I would love to know why he is dying on a frame

**Comment by conundrumer** [comment]
closing in favor of #71
