### ISSUE TITLE
.trk import functionality

### ISSUE THREAD

**Issue by rabidsquirrel117** [conundrumer/lr#77]
Line Rider Advanced's format

**Comment by conundrumer** [comment]
this will be low priority if at all

I recognize it's inconvenient to have to use the command line to convert a track, but I don't want to maintain something according to another developer's file format.

**Comment by rabidsquirrel117** [comment]
It currently impossible for windows users and quite glitchy for mac users. And most people are now using LRA so they wouldn't be able to switch their tracks to LRJS. If you want to get people using LRJS this is a necessary feature.

**Comment by conundrumer** [comment]
okay i'll port this into a separate project: https://github.com/mhenr18/lrtools
